/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/about" |
       "/pages/cart/index" |
       "/pages/category/index" |
       "/pages/forgot-password/index" |
       "/pages/login/index" |
       "/pages/message/index" |
       "/pages/publish/index" |
       "/pages/register/index" |
       "/pages/role/index" |
       "/pages/shelf/index" |
       "/pages/user/index" |
       "/pages-sub/data/price" |
       "/pages-sub/data/forecast" |
       "/pages-sub/data/planting" |
       "/pages-sub/data/forecast-detail" |
       "/pages-sub/data/price-detail" |
       "/pages-sub/data/search" |
       "/pages-sub/farm/index" |
       "/pages-sub/user/verify" |
       "/pages-sub/user/settings" |
       "/pages-sub/user/address" |
       "/pages-sub/user/address-edit" |
       "/pages-sub/user/follow-goods" |
       "/pages-sub/user/follow-shops" |
       "/pages-sub/user/footprints" |
       "/pages-sub/user/purchase-records" |
       "/pages-sub/user/profile" |
       "/pages-sub/user/change-password" |
       "/pages-sub/user/privacy" |
       "/pages-sub/user/agreement" |
       "/pages-sub/user/bind-phone" |
       "/pages-sub/user/bind-email" |
       "/pages-sub/user/change-phone" |
       "/pages-sub/user/change-email" |
       "/pages-sub/goods/detail" |
       "/pages-sub/goods/edit" |
       "/pages-sub/goods/list" |
       "/pages-sub/goods/search" |
       "/pages-sub/order/list" |
       "/pages-sub/order/detail" |
       "/pages-sub/order/create" |
       "/pages-sub/order/review" |
       "/pages-sub/order/logistics" |
       "/pages-sub/order/after-sale/list" |
       "/pages-sub/order/after-sale/detail" |
       "/pages-sub/order/after-sale/apply" |
       "/pages-sub/chat/list" |
       "/pages-sub/chat/detail";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/category/index" | "/pages/message/index" | "/pages/cart/index" | "/pages/user/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
